apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  releaseName: blackbox-exporter
  maxHistory: 3
  interval: 1m0s
  suspend: false
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 50Mi
    config:
      modules:
        http_endpoint:
          prober: http
          timeout: 10s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            valid_status_codes: [200, 204]
            no_follow_redirects: false
            preferred_ip_protocol: "ip4"
