apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  releaseName: loki-stack
  maxHistory: 3
  interval: 1m0s
  suspend: false
  chart:
    spec:
      version: "2.10.2"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    loki:      
      nodeSelector:
        category: tools
        affinity: multi-zones
      enabled: true
      image:
        tag: 2.9.3 
      isDefault: false
      auth_enabled: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 24h
      resources:
        limits:
          memory: 1Gi
          cpu: 500m
        requests:
          memory: 512Mi
          cpu: 100m
    promtail:
      enabled: true
      resources:
        limits:
          memory: 1Gi
          cpu: 500m
        requests:
          memory: 512Mi
          cpu: 100m
