# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: flux-configs
#   namespace: flux-system
# spec:
#   interval: 1m
#   retryInterval: 2m
#   timeout: 5m
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./clusters/resources/flux/envs/prod
#   dependsOn:
#     - name: prometheus
