---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/common-tools/loki/envs/prod
  prune: true
  wait: true
  dependsOn:
    - name: prometheus-v3
