{
 "title": "K8S Pod Metrics",
 "description": "Pod metrics from kube-prometheus-stack and cadvisor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(count by (pod)(count_over_time(kube_pod_info{namespace=~\"$namespace\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU Utilization $pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod, container) (irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage $pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network Traffic $pod",
   "type": "timeseries",
   "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Process/Thread Count $pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container) (container_processes{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{container}} - processes"
    },
    {
     "expr": "sum by (container) (container_threads{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{container}} - threads"
    }
   ]
  },
  {
   "title": "OOM Events $pod",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_oom_events_total{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}